module.exports = {
	COMMUNITY_CHAT:"COMMUNITY_CHAT",
	USER_CONNECTED:"USER_CONNECTED",
	MESSAGE_RECIEVED:"MESSAGE_RECIEVED",
	MESSAGE_SENT:"MESSAGE_SENT",
	MACHINE_DISCONNECTED:"MACHINE_DISCONNECTED",
	MACHINE_BLEED:"MACHINE_BLEED",
	MACHINE_BLEED_FINISH:"MACHINE_BLEED_FINISH",
	MACHINE_BLEED_TOTALS:"MACHINE_BLEED_TOTALS",
	USER_MESSAGE:"USER_MESSAGE",
	USER_DISCONNECTED:"USER_DISCONNECTED",
	USER_CONSUMPTION:"USER_CONSUMPTION",
	USER_CONSUMPTION_TOTALS:"USER_CONSUMPTION_TOTALS",
	TYPING:"TYPING",
	VERIFY_USER:"VERIFY_USER",
	VERIFY_MACHINE:"VERIFY_MACHINE",
	MACHINE_CONNECTED:"MACHINE_CONNECTED",
	MACHINE_REQUEST:"MACHINE_REQUEST",
	MACHINE_CONSUMPTION:"MACHINE_CONSUMPTION",
	MACHINE_CONSUMPTION_TOTALS:"MACHINE_CONSUMPTION_TOTALS",
	LOGOUT:"LOGOUT"
	
}